### ISSUE TITLE
Push (Tabular) Data Package to BigQuery

### ISSUE THREAD

**Issue by rgrp** [okfn/data.okfn.org#127]

**Comment by danfowler** [comment]
Fixed by:
- https://github.com/frictionlessdata/jsontableschema-bigquery-py
- https://github.com/okfn/datapackage-storage-py

**Comment by rgrp** [comment]
:8ball:

**Comment by danfowler** [comment]
Here's the blog post summarizing the changes: http://okfnlabs.org/blog/2016/03/11/frictionless-data-transport-in-python.html
