### ISSUE TITLE
The readme file is not displayed

### ISSUE THREAD

**Issue by genova** [okfn/data.okfn.org#140]
Hi all
After a fork (https://github.com/senegalouvert/data.okfn.org) and a new deployment, the readme file not display
example : http://senegalouvert.org/data/core/population-senegal-recensee

But when I use the DataPackage Viewer ( http://senegalouvert.org/tools ) with this repo 
https://github.com/senegalouvert/population-senegal-recensee it's work

What's wrong who can help, thanks?

**Comment by rgrp** [comment]
@genova I'm not really sure here without some delving so hope you get to the bottom of this (readme stuff is working fine on the main site). I do note there has been an extensive rework of the codebase, and for example, two lists of data packages are now expected - see e.g. https://github.com/okfn/data.okfn.org/commit/01c741ade0fed66294a6e1600bc904d43b56702b

I note e.g. the latter change wasn't really documented and I should explain that this code isn't really designed for others to use but was just intended to power http://data.okfn.org/ (others are very welcome to use but, compared to software designed for others to reuse, we aren't committing to documenting breaking changes in configuration or stuff like that ...).

**Comment by rgrp** [comment]
WONTFIX.

**Comment by genova** [comment]
Bug fix, thank you again for your time

**Comment by rgrp** [comment]
@genova great to know you got this fixed!
