### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [okfn/data.okfn.org#159]
Would JSON-LD serializations be in scope? If yes, then I might be interested to help.

**Comment by rgrp** [comment]
@akuckartz JSON-LD serializations of what (data or metadata)? Definitely welcome help!

**Comment by akuckartz** [comment]
@rgrp JSON-LD for both data and metadata, but low hanging fruit first! I will attempt to prepare a proposal. You may assign this issue to me.

**Comment by rgrp** [comment]
@akuckartz how are you doing here?

**Comment by danfowler** [comment]
Closing in favor of active discussion here: https://github.com/dataprotocols/dataprotocols/issues/218

**Comment by rgrp** [comment]
@danfowler these two things are completely different - this is about outputting JSON-LD serializations for *data* not metadata.

I agree on closing simply because of lack of response but this is not a DUPLICATE of https://github.com/dataprotocols/dataprotocols/issues/218

**Comment by akuckartz** [comment]
Both data and metadata is data. So these issues are related.

**Comment by rgrp** [comment]
@akuckartz do you have any updates here - would love to see anything you can provide.

**Comment by danfowler** [comment]
@rgrp OK. If there's more we can do here, I can re-open and rename the issue so it is clearer to people reading through these issues?

**Comment by rgrp** [comment]
@danfowler agreed and up to @akuckartz - if he is up for doing something and clarifying that is great. Otherwise I suggest we close for now.
