### ISSUE TITLE
http://data.okfn.org Appears to be down

### ISSUE THREAD

**Issue by acouch** [okfn/data.okfn.org#160]
Not sure where to report this but when I visit http://data.okfn.org/ I see:

![screen shot 2015-03-02 at 10 56 46 am](https://cloud.githubusercontent.com/assets/512243/6445629/d92d3ca0-c0ca-11e4-9170-ff0f40a08f4c.png)

**Comment by rgrp** [comment]
Fixed. But need to track what is causing and exception and taking whole app down. This only started happening recently. Will fix asap (site is back up now).

**Comment by acouch** [comment]
Would it be helpful for us to create a Pingdom check to send an alert so it doesn't take folks by surprise? If so you could PM me who to add to the alert.

**Comment by sxren** [comment]
@rgrp a datapackage.json with an empty resources attribute—such as https://raw.githubusercontent.com/RDBinns/datactrl/master/datapackage.json—will crash data.okfn.org. see also https://github.com/datasets/registry/issues/35#issuecomment-74396840

this could be patched with a guard at the view level but it would be ideal to catch it earlier.

**Comment by rgrp** [comment]
@sxren great track down. I think you are right we want something higher level - though fixing immediate bug may be good.

I note that, in theory, heroku should restart the dyno immediately on crash but that does not seem to be happening - see http://stackoverflow.com/questions/19265728/does-heroku-restart-nodejs-server-if-application-crashes

**Comment by sxren** [comment]
@rgrp i don't have in depth knowledge of node on heroku and it's restart behavior. do the logs give any hints?

nunjucks replace has a PR pending to fix issues. i moved the homepage truncation to a filter in https://github.com/okfn/data.okfn.org/pull/162

the fix for empty resources would go in datapackage.js. is that https://github.com/okfn/datapackage.js-deprecated ?

**Comment by rgrp** [comment]
@sxren thanks for these fixes. Re the datapackage.js - yes that is now deprecated and replaced by smaller specific libraries.

I'm wondering we now close this issue or leave open pending the heroku auto restart.

**Comment by sxren** [comment]
@rgrp i think leaving the issue open makes sense pending a fix or at least understanding of the failed heroku restart.

**Comment by rgrp** [comment]
FIXED. At least for now.
