### ISSUE TITLE
Some problem with Data Package viewer

### ISSUE THREAD

**Issue by aborruso** [okfn/data.okfn.org#170]
Hi,
I have seen that it's possible to use the path of a github folder that contains a datapackage.json file, to view a Data Package. This is an example:
[http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fex-geojson](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fex-geojson)

But it's impossible to use a folder URL for one of my repository. The viewer works only if I use the URL of my datapackage.json.
In this way it does not work:
[http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fspaghetti-open-data%2Fbeni-confiscati-aperti%2Ftree%2Fgh-pages%2Fdati%2Fbeni_immobili](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fspaghetti-open-data%2Fbeni-confiscati-aperti%2Ftree%2Fgh-pages%2Fdati%2Fbeni_immobili)

In this way it works:
[http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fspaghetti-open-data%2Fbeni-confiscati-aperti%2Fgh-pages%2Fdati%2Fbeni_immobili%2Fdatapackage.json](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fspaghetti-open-data%2Fbeni-confiscati-aperti%2Fgh-pages%2Fdati%2Fbeni_immobili%2Fdatapackage.json)

What's wrong in my files/procedures?

Thank you

**Comment by rgrp** [comment]
The answer here is simple: the current viewer setup does not work with repo branches if you just provide the github url (if you provide the direct url to the raw data it works because there is no need to compute anything - it just works off that direct url). It would not be hard to improve the viewer to support this:

https://github.com/okfn/data.okfn.org/blob/master/routes/index.js#L181

**Comment by aborruso** [comment]
@rgrp it works only with the master branch?

Thank you

**Comment by rgrp** [comment]
@aborruso if you don't use the raw link then yes it only works with the master branch atm. Would not be hard to fix - see https://github.com/okfn/datapackage-identifier
