### ISSUE TITLE
New (Tabular) Data Package Library (Gem) in Ruby (Incl. Auto-Download, Auto-Import in SQLite n More)

### ISSUE THREAD

**Issue by geraldb** [okfn/data.okfn.org#173]
Hello,
  FYI: You might be interested in (yet another) library for (tabular) data packages in Ruby. The datapak gem lets you, for example, download, import, query data packages. More info @ [textkit/datapak](https://github.com/textkit/datapak). It's all public domain (open source). Still early and rough. Might be great to get the datapak gem listed on the [tools page](http://data.okfn.org/tools). Keep it up. Cheers.

**Comment by rgrp** [comment]
@geraldb this is great and we should get it onto http://data.okfn.org/tools - do you want to do a pull request?

Also does this also mean that you know about this and are interested in using? I know of your awesome sports data and most of that is tabular ... ;-)

**Comment by geraldb** [comment]
@rgrp  Thanks for the prompt answer and kind words. Will send a pull request w/ an update for the tools page.  If you're interested I can send another pull request for adding a blog post to the "[The Data Wrangling Blog](http://okfnlabs.org/blog)" introducing the new tool/library for working with tabular data packages (in Ruby and SQLite).  I'm actually the coder ;-) of the datapak library - so yes I will try to use it.  Thanks for the fantastic (tabular) data package initiative (and documentation) and promoting a simple alternatives for sharing open (structured) data. It's a great inspiration. Keep it up. Cheers.

**Comment by rgrp** [comment]
@geraldb this is awesome - please send pull request for the blog and it is so heartening to hear you find this useful and thanks for your (ongoing) contribution

**Comment by geraldb** [comment]
@rgrp Great. Will try to get a new update for datapak library done and than prepare the blog post and the pull request for the tools page. Have a great weekend. Thanks again. Cheers.

**Comment by rgrp** [comment]
FIXED. http://okfnlabs.org/blog/2015/04/26/datapak.html
