### ISSUE TITLE
Data Package Profile Registry

### ISSUE THREAD

**Issue by pwalsh** [okfn/data.okfn.org#184]
# Idea

We should have a registry of Data Package Profiles: A central location for "official" or "approved" profiles of Data Package. 

This would be community-run - we'd accept pull requests for new profiles, ensure they meet standards we require, etc.

I have an immediate need for something like this, and I think it can generally be useful. Below, I'll describe my immediate need (which is just to illustrate a use case), and then, the MVP I want to implement to meet this need.

## Use case

I want to implement a web form that makes it easy for users to create and edit Data Package descriptors. 

I don't want to hard code this form into certain assumptions. Rather, I'd like to introspect some data structure and generate a form based on it. 

The form should be able to work with any type of Data Package Profile: when passed a profile, it would construct a web form to a allow a user to input all required and recommended fields for that Profile, and optionally, to add extra fields that are not explicitly described in the Profile.

A central registry that provides me with a list of Data Package Profiles, and JSON Schemas that validate them, would enable this.

## MVP

* A github repo with a `registry.json` file
* `registry.json` is an array of objects
* each object represents a Data Package Profile, and has the following keys:
    * id: the identifier for the profile (eg: "openspending")
    * title: the human-readable name for the Profile (eg: "Open Spending Data Package")
    * schema: a URL to a valid json schema (eg: https://raw.githubusercontent.com/dataprotocols/schemas/master/data-package.json)
    * specification: a URL to the specification (eg: http://dataprotocols.org/tabular-data-package/)
* Launch with entries for "Data Package" and "Tabular Data Package"
* Accept new entries via pull request
* New entries need to have a fully documented spec, and a working schema in JSON Schema format

cc @rgrp 
cc @stevage as this will help me provide the basis of a web UI for data packages, which we've talked about

**Comment by rgrp** [comment]
This seems a great idea - i even wonder about a registry.csv rather than .json ;-)

**Comment by pwalsh** [comment]
Truly, up until I wrote the actual issue, I was thinking CSV. I just changed to json in thinking that if this ever grew greatly, and we needed a server for stuff, JSON is maybe better. But for MVP now I'm happy to go with CSV. 

Can I do this as a repo under okfn, or is another location more suitable?

**Comment by rgrp** [comment]
I think either is here on under dataprotocols (?). Similarly with domains - either profiles.dataprotocols.org or profiles.datapackages.org or ...

**Comment by pwalsh** [comment]
https://github.com/dataprotocols/registry

**Comment by davbre** [comment]
Could this just be treated as any other datapackage? I'm thinking the contents of the README file could be encoded in a datapackage.json file.

**Comment by pwalsh** [comment]
@davbre possibly. This is already implemented and has libs using it though. We probably should close this thread:

* https://github.com/dataprotocols/schemas
* http://schemas.datapackages.org/registry.csv
* http://github.com/okfn/datapackage-registry-py
* http://github.com/okfn/datapackage-registry-js

**Comment by davbre** [comment]
@pwalsh that's fair enough

**Comment by rgrp** [comment]
FIXED. See @pwalsh comment.
