### ISSUE TITLE
CSS improvement idea.

### ISSUE THREAD

**Issue by Tjoosten** [okfn/data.okfn.org#194]
What if you support this app also with Less of scss? 

If you want i can code something out for this.

**Comment by danfowler** [comment]
Cool. What specific improvements were you thinking of?

**Comment by Tjoosten** [comment]
Just providing also less or scss for easier development

**Comment by rgrp** [comment]
@Tjoosten happy to get that ... - we generally use less.

**Comment by Tjoosten** [comment]
The problem is i"m only used to scss.

**Comment by rgrp** [comment]
WONTFIX.
