### ISSUE TITLE
Cannot download country list

### ISSUE THREAD

**Issue by 9876-1234** [okfn/data.okfn.org#219]
Application error while downloading at 
http://data.okfn.org/data/core/country-codes/r/country-codes.json

**Comment by tfmorris** [comment]
It worked for me just now. What error did you get? It's helpful if you can provide the error message and as much other information as possible to help track down the problem.

Please try again and if you're still getting an error let us know.

**Comment by rgrp** [comment]
FIXED / WORKSFORME.
